name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite (UTC)
  workflow_dispatch: # Permite rodar manualmente pelo GitHub

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha 🐍
        uses: Platane/snk@v3
        with:
          github_user_name: anapaulaalves
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publicar na branch "output"
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
